project:
  type: default
  output-dir: _output

book:
  title: "Perancangan Sistem Deteksi Kecurangan pada Platform GZCTF Menggunakan Algoritma Two-Stage Similarity Analysis dan Weighted Risk Scoring"
  author: "Dimas Maulana"
  chapters:
    - index.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee
format:
  html:
    css: styles.css
    toc: true
    number-sections: true
    papersize: a4
    geometry:
      - top=25mm
      - left=35mm
      - right=25mm
      - bottom=25mm
    mainfont: "Times New Roman"
    mermaid:
      theme: neutral
      flowchart:
        curve: stepBefore
    fontsize: 12pt
    linestretch: 1.5
  pdf:
    include-before-body:
      - cover.tex
      - approval.tex
    toc: false
    number-sections: true
    papersize: a4
    geometry:
      - top=25mm
      - left=35mm
      - right=25mm
      - bottom=25mm
    mainfont: "Times New Roman"
    mermaid:
      theme: neutral
      flowchart:
        curve: stepBefore
    fontsize: 12pt
    linestretch: 1.5
  docx:
    toc: false
